// frontend/src/types.ts

// Represents the structure of a balance for a single asset
export interface AssetBalance {
  free: number;
  used: number;
  total: number;
}

// Represents balances for multiple assets on a single exchange
export interface ExchangeBalance {
  exchange: string;
  balances: Record<string, AssetBalance>; // e.g., {"USDT": AssetBalance, "BTC": AssetBalance}
  timestamp: string; // ISO 8601 datetime string
  error?: string | null; // Optional error message if fetching balances failed
}

// Represents an entry in an order book (bid or ask)
export interface OrderBookEntry {
  price: number;
  quantity: number; // Changed from amount for consistency with ccxt
}

// Represents the order book for a specific trading pair on an exchange
export interface OrderBook {
  exchange: string;
  pair: string; // Changed from symbol for consistency
  bids: OrderBookEntry[];
  asks: OrderBookEntry[];
  timestamp: string; // ISO 8601 datetime string
}

// Represents a single trade leg (buy or sell)
export interface TradeLeg {
  exchange: string;
  pair: string; // Changed from symbol
  side: "buy" | "sell";
  type: "market" | "limit"; // Added order type
  price: number;     // Price in quote currency
  amount_base: number;    // Amount in base currency
  amount_quote: number;   // Amount in quote currency
  fee_amount?: number;       // Fee amount
  fee_currency?: string;   // Fee currency
  timestamp: string; // ISO 8601 datetime string
  status: "open" | "closed" | "canceled" | "expired" | "rejected"; // Added status
}

// Represents a completed arbitrage trade (both buy and sell legs)
export interface ArbitrageTrade {
  id: string; // Unique ID for the arbitrage event
  opportunity_id?: string; // ID of the opportunity that led to this trade (optional)
  timestamp: string; // ISO 8601 datetime string
  pair: string; // Changed from symbol
  buy_trade: TradeLeg;
  sell_trade: TradeLeg;
  profit_percentage: number;
  profit_quote: number; // Net profit in quote currency (e.g., USDT)
  is_test_trade: boolean; // Changed from is_test
  status: "pending" | "completed" | "failed" | "partially_filled";
}

// Represents a potential arbitrage opportunity
export interface ArbitrageOpportunity {
  id: string;
  timestamp: string; // ISO 8601 datetime string
  pair: string;
  profit_percentage: number;
  buy_exchange: string;
  sell_exchange: string;
  buy_price: number;
  sell_price: number;
  potential_trade_volume_quote?: number; // Max amount in quote currency (e.g. USDT)
}

// Represents an alert or system message
export interface AlertMessage {
  id?: string; // Optional, can be generated by frontend if missing
  type: string; // More flexible, e.g., "system_error", "trade_executed", "exchange_disconnected"
  message: string;
  timestamp: string; // ISO 8601 datetime string
  severity: "info" | "warning" | "error" | "critical";
  entity_name?: string;    // e.g., pair, exchange_id, "global"
  // can_reactivate?: boolean; // This logic might be better handled by UI based on alert type/entity
}

export interface FailsafeStatusData {
  disabled_pairs: Record<string, { reason: string; cooldown_until?: string | null; attempts?: number }>;
  disabled_exchanges: Record<string, { reason: string; cooldown_until?: string | null; attempts?: number }>;
  global_trading_halt: boolean;
  global_halt_reason?: string | null;
  global_halt_timestamp?: string | null;
  historical_high_balance_usdt?: number;
}

// Represents the overall status of the bot from the backend (part of WebSocket payload)
export interface BotStatusPayload {
  is_bot_running: boolean;
  current_mode: "idle" | "live" | "test_simulating";
  connected_exchanges: string[];
  websocket_connected: boolean; // Managed by frontend, but can be part of initial payload
  last_status_update_ts: string; // ISO 8601 datetime string
  active_alerts: AlertMessage[];
  failsafe_status: FailsafeStatusData;
  live_total_trades?: number;
  live_total_profit?: number;
}

// For test mode settings sent to backend
export interface TestModeSettings {
  usdt_capital_per_exchange: number; // Changed from usdt_cap
  asset_capital_usd_per_pair: number;  // Changed from asset_cap, now represents USD value
  buffer_percentage?: number; // Optional: Stored as percentage e.g. 0.01 for 0.01%
  exchanges?: string[]; // Optional: specific exchanges for test, otherwise all connected
}

// Specific payload for test simulation status updates (part of WebSocket payload)
export interface TestSimulationStatusPayload {
  status: "IDLE" | "STARTING" | "RUNNING" | "STOPPED" | "ERROR" | "UNKNOWN";
  message?: string;
  active_since?: string | null; // ISO timestamp
  total_test_trades: number;
  total_test_profit: number;
}

// Structure for the full payload received via WebSocket initial_status or bot_status_update
export interface FullStatusUpdatePayload {
  bot_status: BotStatusPayload;
  test_simulation_status: TestSimulationStatusPayload;
  recent_trades: ArbitrageTrade[];
  recent_opportunities: ArbitrageOpportunity[];
  exchange_balances: ExchangeBalance[];
}

// For WebSocket messages
export interface WebSocketMessage {
  type: "initial_status" | "bot_status_update" | "new_trade" | "new_opportunity" | "new_alert" | "exchange_connected" | "exchange_disconnected" | "pong";
  payload: FullStatusUpdatePayload | ArbitrageTrade | ArbitrageOpportunity | AlertMessage | { exchange: string } | { timestamp: string } | any; // Adjust 'any' based on specific non-full payloads
}

// For API responses that are simple success/failure messages
export interface ActionResponse {
  success: boolean;
  message: string;
  data?: any; // Optional data field for some responses
}

// For connecting to an exchange
export interface ExchangeCredentials {
  exchange: string;
  api_key: string;
  api_secret: string;
  additional_params?: Record<string, any>; // For things like passphrase for Kraken
}

// For starting the bot
export interface StartBotRequest {
  mode: "live" | "test";
  test_settings?: TestModeSettings;
}

// For reactivating a failsafe
export interface ReactivateRequest {
  type: "pair" | "exchange" | "global";
  entity_name?: string; // Name of the pair or exchange, not needed for global
}

